<template>
    <div class="container">
        <!--
        <div v-for="(finding, index) in findings" :key="index" class="row">
                <div class="col-sm">
                {{ finding.AccountId }}
                </div>
                <div class="col-sm">
                {{ finding.AccountName }}
                </div>
                <div class="col-sm">
                {{ finding.Finding }}
                </div>
        
        </div>
        -->
        <br>
        <a href="#" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" @click.prevent="download_table_as_csv('export');">Download Results as CSV</a>
        <table class="table" id="export">
          <thead>
            <tr>
              <th v-for="(title, index) in titles" :key="index" scope="col">{{title}}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(finding, index) in findings" :key="index">
              <td v-for="entry in finding">{{ entry }}</td>
            </tr>
          </tbody>
        </table>
    </div>

</template>

<script>
export default {
    /**
     * accounts -> current list of accounts
     * findings -> current list of findings, generated by QueryPage
     * titles -> list of column names selected and displayed on the table
     */
    props: ['accounts', 'findings', 'titles'],
    created() {
        
    },
    data() {
        return {
            
        }
    },
    methods: {
        /**
         * Helper function that downloads the current selected table as CSV
         * Source: https://stackoverflow.com/questions/15547198/export-html-table-to-csv-using-vanilla-javascript
         */
        download_table_as_csv(table_id, separator = ',') {
        // Select rows from table_id
        var rows = document.querySelectorAll('table#' + table_id + ' tr');
        // Construct csv
        var csv = [];
        for (var i = 0; i < rows.length; i++) {
            var row = [], cols = rows[i].querySelectorAll('td, th');
            for (var j = 0; j < cols.length; j++) {
                // Clean innertext to remove multiple spaces and jumpline (break csv)
                var data = cols[j].innerText.replace(/(\r\n|\n|\r)/gm, '').replace(/(\s\s)/gm, ' ')
                // Escape double-quote with double-double-quote (see https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv)
                data = data.replace(/"/g, '""');
                // Push escaped string
                row.push('"' + data + '"');
            }
            csv.push(row.join(separator));
        }
        var csv_string = csv.join('\n');
        // Download it
        var filename = 'export_' + table_id + '_' + new Date().toLocaleDateString() + '.csv';
        var link = document.createElement('a');
        link.style.display = 'none';
        link.setAttribute('target', '_blank');
        link.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv_string));
        link.setAttribute('download', filename);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        }
    }
}
</script>